---
title: "Run ShortReadsPhaser"
---

```{r setup, include=FALSE}
# create output directories
outdir_best_hits         <- file.path(currentdir, "01_best_hits")
outdir_best_hits_cds     <- file.path(outdir_best_hits, "cds")
outdir_best_hits_flanked <- file.path(outdir_best_hits, "flanked")

outdir_mapping           <- file.path(currentdir, "02_mapping")
outdir_variant_calls     <- file.path(currentdir, "03_variant_calling")
outdir_haplotypes        <- file.path(currentdir, "04_haplotypes")
outdir_blocks_cds        <- file.path(currentdir, "05_blocks_cds")

outdir_assignment        <- file.path(currentdir, "06_assignment")
outdir_mafftadd          <- file.path(outdir_assignment, "01_mafftadd")
outdir_epa_ng            <- file.path(outdir_assignment, "02_epa_ng")
sapply(c(outdir_best_hits_cds, outdir_best_hits_flanked, outdir_mapping, outdir_variant_calls, outdir_haplotypes, outdir_blocks_cds, outdir_mafftadd, outdir_epa_ng), function(x) {
  if (!dir.exists(x)) { dir.create(x, recursive=T) }})
```

```{r}
# extract CAPTUS best hits
fn_target_loci_flanked <- file.path(outdir_best_hits, "target_loci_flanked.fna")
fn_target_loci_cds     <- file.path(outdir_best_hits, "target_loci_cds.fna")
f_extract_captus_best_hits(params$file_query_matches_flanked, fn_target_loci_flanked)
f_extract_captus_best_hits(params$file_query_matches_cds, fn_target_loci_cds)

# extract per-locus best hit
f_split_captus_best_hits(fn_target_loci_flanked, outdir_best_hits_flanked)
f_split_captus_best_hits(fn_target_loci_cds, outdir_best_hits_cds)
```

```{r mapping-variants}
# retrieve FASTQ files
fn_fastq_r1 <- file.path(params$dir_fastq_gz, paste0(params$sample, "_R1.fastq.gz"))
fn_fastq_r2 <- file.path(params$dir_fastq_gz, paste0(params$sample, "_R2.fastq.gz"))
if (!all(file.exists(fn_fastq_r1, fn_fastq_r2))) {
    log4r::error(fn_logger, "Error: missing R1 and/or R2 FASTQ files. Exited.")
    knitr::knit_exit()
}

# run BWA-MEM and sort/deduplicate reads
fn_bam_sort  <- file.path(outdir_mapping, paste0(params$sample, ".sorted.bam"))
fn_bam_dedup <- file.path(outdir_mapping, paste0(params$sample, ".dedup.bam"))
fn_depth     <- file.path(outdir_mapping, "locus_depth.tsv")
f_bwa_mem(fn_target_loci = fn_target_loci_flanked,
          fn_fastq_r1    = fn_fastq_r1,
          fn_fastq_r2    = fn_fastq_r2,
          fn_bam_sort    = fn_bam_sort,
          fn_bam_dedup   = fn_bam_dedup,
          fn_depth       = fn_depth,
          thread         = params$thread,
          exe_bwa        = params$exe_bwa,
          exe_samtools   = params$exe_samtools)

# run Bcftools for variant calling
fn_vcf_gz          <- file.path(outdir_variant_calls, paste0(params$sample, ".vcf.gz"))
fn_filtered_vcf_gz <- file.path(outdir_variant_calls, paste0(params$sample, ".filtered.vcf.gz"))
f_variant_calling(fn_target_loci     = fn_target_loci_flanked,
                  fn_bam             = fn_bam_dedup,
                  fn_vcf_gz          = fn_vcf_gz,
                  fn_vcf_gz_filtered = fn_filtered_vcf_gz,
                  min_depth          = 12,
                  max_depth          = 150,
                  thread             = params$thread,
                  exe_bcftools       = params$exe_bcftools)
```

```{r whatshap}
# run WhatsHap
fn_phased_vcf      <- file.path(outdir_variant_calls, paste0(params$sample, ".phased.vcf"))
fn_phased_vcf_gz   <- file.path(outdir_variant_calls, paste0(params$sample, ".phased.vcf.gz"))
fn_blocks_whatshap <- file.path(outdir_variant_calls, "blocks_whatshap.tsv")
f_whatshap(fn_target_loci     = fn_target_loci_flanked,
           fn_vcf_gz_filtered = fn_filtered_vcf_gz,
           fn_bam             = fn_bam_dedup,
           fn_phased_vcf      = fn_phased_vcf,
           fn_blocks_whatshap = fn_blocks_whatshap,
           exe_whatshap       = params$exe_whatshap)

# generate putative haplotypes
df_blocks_whatshap <- data.table::fread(fn_blocks_whatshap)
colnames(df_blocks_whatshap) <- c("sample", "locus", "PS", "from", "to", "variants")

# exclude indels
fn_snps_vcf_gz <- file.path(outdir_variant_calls, paste0(params$sample, ".phased.snps.vcf.gz"))
system(paste(params$exe_bcftools, "view", "-v snps -Oz", "-o", fn_snps_vcf_gz, fn_phased_vcf_gz))
system(paste(params$exe_bcftools, "index", "-f", fn_snps_vcf_gz))

# iterate over blocks
for (i in seq_len(nrow(df_blocks_whatshap))) {
    # open target file
    fn_refseq <- file.path(outdir_best_hits_flanked, paste0(df_blocks_whatshap$locus[i], ".fna"))
    refseq    <- Biostrings::readBStringSet(fn_refseq)

    # extract variables
    locus  <- df_blocks_whatshap$locus[i]
    ps     <- df_blocks_whatshap$PS[i]
    bstart <- df_blocks_whatshap$from[i]
    bend   <- df_blocks_whatshap$to[i]
    len    <- length(refseq[[1]])

    # create a BED file
    fn_mask_bed <- file.path(outdir_haplotypes, paste0(locus, ".PS", ps, ".mask.bed"))
    mask        <- data.frame(chrom=locus, from=c(0, bend), to=c(bstart-1, len))
    mask        <- mask[mask$from < mask$to, ] 
    data.table::fwrite(mask, file=fn_mask_bed, sep="\t", quote=FALSE, col.names=F)

    # run Bcftools consensus
    fn_hap1 <- file.path(outdir_haplotypes, paste0(locus, ".PS", ps, "_h1.fna"))
    fn_hap2 <- file.path(outdir_haplotypes, paste0(locus, ".PS", ps, "_h2.fna"))
    f_generate_haplotypes(fn_target_loci = fn_refseq,
                          fn_bed         = fn_mask_bed,
                          fn_snps_vcf    = fn_snps_vcf_gz,
                          fn_hap1        = fn_hap1,
                          fn_hap2        = fn_hap2,
                          exe_bcftools   = params$exe_bcftools)

    # update the sequence header
    for (h in c("h1", "h2")) {
        fn_hap     <- file.path(outdir_haplotypes, paste0(locus, ".PS", ps, "_", h, ".fna"))
        seq        <- Biostrings::readBStringSet(fn_hap)
        names(seq) <- paste0(locus, "_PS", ps, "_", h)
        Biostrings::writeXStringSet(seq, filepath=fn_hap)
    }
}
```

```{r block-cds}
# output variables
df_exons  <- data.table::data.table()
ls_failed <- c()

# extract list of loci
ls_locus <- list.files(outdir_best_hits_flanked, pattern="\\.fna$", recursive=F, full.names=F)
ls_locus <- gsub("\\.fna$", "", ls_locus)

# iterate over loci
for (locus in ls_locus) {
    # input files
    fn_cds     <- file.path(outdir_best_hits_cds, paste0(locus, ".fna"))
    fn_flanked <- file.path(outdir_best_hits_flanked, paste0(locus, ".fna"))
    if (!file.exists(fn_cds)) {
        ls_failed <- c(ls_failed, paste0(locus, ": no CDS best hit"))
        next
    }

    # extract exon coordinates
    exons <- f_locate_exons(fn_cds, fn_flanked)
    if (is.null(exons)) {
        ls_failed <- c(ls_failed, paste0(locus, ": CDS could not be aligned to the flanked sequence"))
        next
    }

    # update the output data.frame
    df_exons <- rbind(df_exons, data.table::data.table(locus=locus, exon=seq_len(nrow(exons)), exons))

    # cextract the CDS out of every block haplotype of this locus
    fn_haps <- list.files(outdir_haplotypes, pattern=paste0("^", locus, "\\.PS.*_h[12]\\.fna$"), full.names=TRUE)
    if (length(fn_haps) == 0) {
        next
    }

    # combine all CDS
    block_cds <- do.call(c, lapply(fn_haps, f_extract_cds, exons=exons))
    Biostrings::writeXStringSet(block_cds, filepath=file.path(outdir_blocks_cds, paste0(locus, ".fna")))
}

# save the exon table and the list of failed loci
fn_exon_table  <- file.path(outdir_blocks_cds, "exon_table.tsv")
fn_exon_failed <- file.path(outdir_blocks_cds, "exon_failed.txt")

data.table::fwrite(df_exons, file=fn_exon_table, sep="\t", quote=F)
readr::write_lines(ls_failed, file=fn_exon_failed)

log4r::info(fn_logger, paste0("Exon tables: ", length(unique(df_exons$locus)), " loci ",
                              "(", sum(df_exons$strand[!duplicated(df_exons$locus)] == "-"), " minus strand); ",
                              "failed: ", length(ls_failed)))
```

```{r add-query}
# open the best model for each gene tree
df_genetree_model <- data.table::fread(params$file_backbone_genetree_models)

# create doSNOW cluster
nwcl <- makeCluster(params$thread)
registerDoSNOW(nwcl)

# iterate over loci
foreach (locus = ls_locus) %dopar% {
    # input files
    fn_query <- file.path(outdir_blocks_cds, paste0(locus, ".fna"))
    fn_ref   <- file.path(params$dir_backbone_alignment, paste0(locus, ".fna"))
    if (!all(file.exists(fn_query, fn_ref))) {
        return(NULL)
    }

    # MAFFT --add
    fn_output_alignment <- file.path(outdir_mafftadd, paste0(locus, ".fna"))
    f_mafft_add(fn_ref    = fn_ref,
                fn_sample = fn_query,
                fn_out    = fn_output_alignment,
                exe_mafft = params$exe_mafft)

    # remove '_R_' for reverse-complemented sequence
    aln <- Biostrings::readBStringSet(fn_output_alignment)
    names(aln) <- gsub("^_R_", "", names(aln))
    Biostrings::writeXStringSet(aln, filepath=fn_output_alignment)

    # split the reference and query sequences for EPA-NG
    dir_output    <- file.path(outdir_epa_ng, locus)
    if (!dir.exists(dir_output)) {
        dir.create(dir_output, recursive=T)
    }

    fn_epa_ng_log <- file.path(dir_output, paste0(locus, ".log"))
    system(paste(params$exe_epa_ng, "--split", fn_ref, fn_output_alignment, "-w", dir_output, ">>", fn_epa_ng_log))

    # place the query on each gene tree
    fn_ref_tree <- file.path(params$dir_backbone_genetrees, paste0(locus, ".treefile"))
    substitution_model <- f_iqtree2epa_ng_model(df_genetree_model$model[df_genetree_model$locus==locus])

    f_epa_ng(fn_ref     = file.path(dir_output, "reference.fasta"),
             fn_query   = file.path(dir_output, "query.fasta"),
             fn_tree    = fn_ref_tree,
             model      = substitution_model,
             outdir     = dir_output,
             fn_log     = fn_epa_ng_log,
             exe_epa_ng = params$exe_epa_ng)

    # translate placements into lineage name
    f_gappa_assign(fn_jplace = file.path(dir_output, "epa_result.jplace"),
                   fn_taxon  = params$file_taxonomy_metadata,
                   outdir    = file.path(dir_output, "assign"),
                   log_file  = fn_epa_ng_log,
                   exe_gappa = params$exe_gappa)
}

stopCluster(nwcl)
```

```{r block-assignment}
# read gappa assignments and decide the identity of each block
df_assign  <- f_read_gappa_assignments(outdir_epa_ng, params$taxonomy_rank)
ls_results <- f_assign_blocks(df_assign, params$min_alwr)

# save output data.frames
data.table::fwrite(ls_results$blocks, file=file.path(outdir_assignment, "block_assignments.tsv"), sep="\t", quote=F)
data.table::fwrite(ls_results$pairs, file=file.path(outdir_assignment, "lineage_pairs.tsv"), sep="\t", quote=F)

# update log files
n_decision <- table(ls_results$blocks$decision)
readr::write_lines(c("", paste0("Parental lineages: A = ", ls_results$lineage_A, ", B = ", ls_results$lineage_B),
                         paste0("Number of confidently-placed blocks: ", ls_results$pairs$n_blocks[1], " of ", sum(ls_results$pairs$n_blocks)),
                         paste0("Decisions: ", paste(names(n_decision), n_decision, sep="=", collapse=", ")))
                   con=fn_log, append=T)

if (ls_results$lineage_A == ls_results$lineage_B) {
    log4r::warn(fn_logger, "Most common pair is a single lineage. Please rerun with a finer taxonomy_rank")
}
```